Added stepup client method
bitwarden/passwordless-client-js pull request #33
Opened 2024-04-23 15:06 UTC by jrmccannon

### Ticket
- Closes [PAS-299](https://bitwarden.atlassian.net/browse/PAS-299)

### Description
This adds the `stepup` client method for authenticating a user for a specific purpose or action.

### Shape
`Stepup` is an overload for the `signin` method with the addition of the purpose to `signinBegin`.

### Checklist
I did the following to ensure that my changes were tested thoroughly:
- Tested the generated js file in the Passwordless dotnet sdk repo and used that instead of the cdn.

I did the following to ensure that my changes do not introduce security vulnerabilities:
N/A

2024-05-02 11:06 UTC, jonashendrickx requested changes
Maybe do the formatting separately

2024-05-30 15:10 UTC, jrmccannon commented
Formatting changes can be found in this branch

https://github.com/bitwarden/passwordless-client-js/pull/41

2024-05-30 17:15 UTC, Tyrrrz submitted a review, later dismissed

2024-05-31 14:00 UTC, jrmccannon commented
> Maybe do the formatting separately

Formatting changes have been applied @jonashendrickx

2024-06-04 13:36 UTC, jonashendrickx submitted a review, later dismissed

2024-06-10 13:05 UTC, jonashendrickx commented on src/passwordless.ts
> +            console.error(caughtError);
Was logging this intentional?

2024-06-10 13:06 UTC, jonashendrickx submitted a review, later dismissed

2024-06-10 13:16 UTC, jrmccannon commented on src/passwordless.ts
> +            console.error(caughtError);
It is the pattern we use in register and sign-in so I wanted to stay consistent.

2024-06-11 13:53 UTC, Tyrrrz approved these changes

2024-06-11 13:53 UTC, Tyrrrz commented
Let's merge this before #45 to reduce merge conflicts

2024-06-11 17:42 UTC, merged