Allow client-version tracking for other client SDK.
bitwarden/passwordless-client-js pull request #51
Opened 2024-06-23 12:08 UTC by jonashendrickx

### Description

If we use the Javascript client SDK in other SDK for use in Blazor Web Assembly, we are recording 'Client-Version' header with value 'js-1.1.0'. We should allow to change this.

We don't need to document the builder pattern as generally others won't need it.

It will allow us to track bugs for efficiently rather than playing ping pong with customer service trying to obtain the required information from the customer.

### Shape

### Screenshots

### Checklist

I did the following to ensure that my changes were tested thoroughly:

- \_\_

I did the following to ensure that my changes do not introduce security vulnerabilities:

- \_\_

2024-06-23 15:29 UTC, abergs commented on src/passwordless.ts
> +  constructor(config: AtLeast<Config, 'apiKey'>, clientVersion?: string) {
I would suggest not exposing this in the constructor since that is a "hot path" for how end users call our api.

What about a less visible way, like allowing changing clientVersion through a public method, e.g. `SetClientVersion(...)` instead?

2024-06-23 15:32 UTC, abergs requested changes
Overall idea sounds good, but I would suggest changing a few things:

* Add this meta data through another mechanism than the constructor to reduce visibility
* Any additional version is appended to existing info, not replacing it. So if you use this in blazor and call `withClientVersion("blazor-1.2.0")` it would show up as `js-1.1.0+blazor-1.2.0` since that represents both the actual client-chain.

2024-06-24 18:09 UTC, jonashendrickx commented on src/passwordless.ts
> +  constructor(config: AtLeast<Config, 'apiKey'>, clientVersion?: string) {
Check if you like these changes @abergs

2024-06-24 19:06 UTC, abergs requested changes

2024-06-24 19:06 UTC, abergs commented on src/passwordless.ts
> +    this._clientVersion = value;
This would still replace the value rather appending it unless I've missed something? @jonashendrickx

2024-06-25 06:57 UTC, jonashendrickx commented on src/passwordless.ts
> +    this._clientVersion = value;
@abergs Yes, the goal is to replace it, so we can properly track the Blazor WebAssembly SDK or any other Javascript Client SDK derived SDKs.

We now have:

- js-1.0.0
- android-1.0.0

But if I implement the Javascript Client SDK in Blazor WebAssembly, it would currently send the header with value 'js-1.0.0' rather than 'blazorwasm-1.0.0'.

It would allow you to make it easier to track which SDK has issues and give you the ability to see which ones are the most frequently used. Allowing you to either drop support or determine backwards compatibility.

2024-06-25 13:39 UTC, abergs commented on src/passwordless.ts
> +    this._clientVersion = value;
I understand, but wouldn't sending js-1.0.0+blazorwasm-1.0.0 transmit more information since the blazorwasm SDK just wraps the js client? For example, we would be able to see in the error log that the js-client used was 1.1 and it was used with blazorwasm-1.3?

2024-06-25 18:00 UTC, Tyrrrz commented on src/passwordless.ts
> +  public set clientVersion(value: string) {
Why not set the version from the constructor instead? From my understanding, it wouldn't really  be changed throughout the lifetime of the class, right?

2024-06-25 23:25 UTC, abergs commented on src/passwordless.ts
> +  public set clientVersion(value: string) {
Pee my request. Because I wanted to limit the visibility of this feature

2024-06-27 18:35 UTC, jonashendrickx commented on src/passwordless.ts
> +    this._clientVersion = value;
II am fine with either.

2024-06-27 22:12 UTC, abergs commented on src/passwordless.ts
> +    this._clientVersion = value;
@jonashendrickx I think appending will be valuable. Make that change and we're good to go on this.

2024-06-28 08:04 UTC, jonashendrickx commented on src/passwordless.ts
> +    this._clientVersion = value;
@abergs Prepending or appending? If we prepend, it makes it easier to find the actual SDK implementing the javascript SDK without having to read the entire line.

2024-06-28 10:17 UTC, abergs commented on src/passwordless.ts
> +    this._clientVersion = value;
@jonashendrickx Whatever you think is best we'll go with!

2024-07-03 08:13 UTC, jonashendrickx commented on src/passwordless.ts
> +    this._clientVersion = value;
@abergs ready

2024-07-19 11:54 UTC, abergs approved these changes

2024-07-19 11:54 UTC, merged